// Code generated by entimport, DO NOT EDITe
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Transaction struct {
	ent.Schema
}

func (Transaction) Fields() []ent.Field {
	return []ent.Field{field.Int("id"),
		field.Int("user_id").Optional(),
		field.Int("category_id").Optional(),
		field.Enum("type").Values("income", "expense"),
		field.Float("amount"), field.String("currency"),
		field.String("description").Optional(),
		field.Float("conversion_rate").Optional(),
		field.Time("tx_date"),
		field.Time("created_at").Optional(),
		field.Time("updated_at").Optional()}
}
func (Transaction) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).Ref("transactions").Unique().Field("user_id"),
		edge.From("category", Category.Type).Ref("transactions").Unique().Field("category_id"),
	}
}
func (Transaction) Annotations() []schema.Annotation {
	return nil
}
