// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.Int("id"),
		field.Int("account_id").Unique(),
		field.String("first_name").Optional(),
		field.Time("created_at").Optional(),
		field.Time("last_seen").Optional(),
		field.String("currency").Optional(),
		field.String("locale").Optional(),
		field.String("timezone").Optional()}
}
func (User) Edges() []ent.Edge {
	return []ent.Edge{edge.To("categories", Category.Type), edge.To("transactions", Transaction.Type)}
}
func (User) Annotations() []schema.Annotation {
	return nil
}
