// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"test-go2/ent/category"
	"test-go2/ent/transaction"
	"test-go2/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionCreate is the builder for creating a Transaction entity.
type TransactionCreate struct {
	config
	mutation *TransactionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TransactionCreate) SetUserID(v int) *TransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableUserID(v *int) *TransactionCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *TransactionCreate) SetCategoryID(v int) *TransactionCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCategoryID(v *int) *TransactionCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *TransactionCreate) SetType(v transaction.Type) *TransactionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TransactionCreate) SetAmount(v float64) *TransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *TransactionCreate) SetCurrency(v string) *TransactionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TransactionCreate) SetDescription(v string) *TransactionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableDescription(v *string) *TransactionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetConversionRate sets the "conversion_rate" field.
func (_c *TransactionCreate) SetConversionRate(v float64) *TransactionCreate {
	_c.mutation.SetConversionRate(v)
	return _c
}

// SetNillableConversionRate sets the "conversion_rate" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableConversionRate(v *float64) *TransactionCreate {
	if v != nil {
		_c.SetConversionRate(*v)
	}
	return _c
}

// SetTxDate sets the "tx_date" field.
func (_c *TransactionCreate) SetTxDate(v time.Time) *TransactionCreate {
	_c.mutation.SetTxDate(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransactionCreate) SetCreatedAt(v time.Time) *TransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableCreatedAt(v *time.Time) *TransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TransactionCreate) SetUpdatedAt(v time.Time) *TransactionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TransactionCreate) SetNillableUpdatedAt(v *time.Time) *TransactionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TransactionCreate) SetID(v int) *TransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TransactionCreate) SetUser(v *User) *TransactionCreate {
	return _c.SetUserID(v.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *TransactionCreate) SetCategory(v *Category) *TransactionCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_c *TransactionCreate) Mutation() *TransactionMutation {
	return _c.mutation
}

// Save creates the Transaction in the database.
func (_c *TransactionCreate) Save(ctx context.Context) (*Transaction, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransactionCreate) SaveX(ctx context.Context) *Transaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransactionCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Transaction.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := transaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Transaction.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Transaction.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Transaction.currency"`)}
	}
	if _, ok := _c.mutation.TxDate(); !ok {
		return &ValidationError{Name: "tx_date", err: errors.New(`ent: missing required field "Transaction.tx_date"`)}
	}
	return nil
}

func (_c *TransactionCreate) sqlSave(ctx context.Context) (*Transaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransactionCreate) createSpec() (*Transaction, *sqlgraph.CreateSpec) {
	var (
		_node = &Transaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transaction.Table, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(transaction.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ConversionRate(); ok {
		_spec.SetField(transaction.FieldConversionRate, field.TypeFloat64, value)
		_node.ConversionRate = value
	}
	if value, ok := _c.mutation.TxDate(); ok {
		_spec.SetField(transaction.FieldTxDate, field.TypeTime, value)
		_node.TxDate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.UserTable,
			Columns: []string{transaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.CategoryTable,
			Columns: []string{transaction.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TransactionCreateBulk is the builder for creating many Transaction entities in bulk.
type TransactionCreateBulk struct {
	config
	err      error
	builders []*TransactionCreate
}

// Save creates the Transaction entities in the database.
func (_c *TransactionCreateBulk) Save(ctx context.Context) ([]*Transaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Transaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransactionCreateBulk) SaveX(ctx context.Context) []*Transaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
